<?php

namespace CASTOR\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * date_trimestrielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class date_trimestrielRepository extends EntityRepository
{
}
