<?php

namespace CASTOR\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MatieresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatieresRepository extends EntityRepository
{
}
