<?php

namespace CASTOR\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParamRepository extends EntityRepository
{
}
